apiVersion: apps/v1
kind: Deployment
metadata:
    name: nexo-app
spec:
    selector:
        matchLabels:
            app: nexo
    replicas: 2
    template:
        metadata:
            labels:
                app: nexo
        spec:
            containers:
                - name: nexo
                  imagePullPolicy: Never
                  image: defnqta/nexo
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: nexo
spec:
    type: NodePort
    selector:
        app: nexo
    ports:
        - port: 8080
          targetPort: 8080
