name: Minikube

on: [push]

jobs:
  example:
    name: Minikube-Kubernetes Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.3
        with:
          minikube version: 'v1.24.0'
          kubernetes version: 'v1.23.0'
          github token: ${{ secrets.LOGIN_TOKEN }}
      - name: Interact with the cluster
        run: kubectl get nodes
      - name: Deploy to minikube and list
        run:
           -- kubectl apply -f deployment.yaml
           -- kubectl get pods, svc --all-namespaces
